# Generated by Django 5.1.4 on 2024-12-19 08:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0002_potentialuser_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialuser',
            name='os',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='potentialuser',
            name='tier',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
