# Generated by Django 5.1.4 on 2024-12-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0003_alter_potentialuser_os_alter_potentialuser_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialuser',
            name='os',
            field=models.CharField(max_length=10),
        ),
    ]
