# Generated by Django 5.1.4 on 2024-12-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingPage', '0004_alter_potentialuser_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialuser',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
